apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-antd-ssr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antd-ssr
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: antd-ssr
    spec:
      containers:
        - name: antd-ssr
          image: registry.cn-hongkong.aliyuncs.com/hocgin/antd-ssr:latest
          imagePullPolicy: Always
          args: [ "--spring.profiles.active=${ACTIVE}" ]
          ports:
            - name: web-port
              containerPort: 21001
          envFrom:
            - configMapRef:
                name: cm-service-env
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: web-port
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: web-port
            initialDelaySeconds: 100
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: sv-antd-ssr
spec:
  type: NodePort
  ports:
    - port: 21001
      targetPort: 21001
      protocol: TCP
  selector:
    app: antd-ssr
